### ISSUE TITLE
Make 'created by' variable

### ISSUE THREAD

**Issue by janis-ax** [datavolo-io/hatch-datavolo-nar#10]
Hi everyone, 

If possible, could we change the following line: https://github.com/datavolo-io/hatch-datavolo-nar/blob/4a79844c640ca1a3eb8c326b32d53fe13f33c7b5/src/hatch_datavolo_nar/builder.py#L61 
to make it variable. So that I can change the value, for example, to `janis-ax` within my `project.toml`. 

Since hatch has some [standards](https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table) for metadata, I think we should use them instead of a custom field. 

My suggestion is to use the authors key: `f"Created-By: {metadata.core.authors}",`

**Comment by exceptionfactory** [comment]
Thanks for requesting this new feature @janis-ax.

The `Created-By` field value reflects the packaging tool responsible for the NAR, versus the author. This follows the same approach as the Apache NiFi NAR Maven Plugin:

https://github.com/apache/nifi-maven/blob/558039eb04889f83ad39592bbc742ce20748591f/src/main/java/org/apache/nifi/NarMojo.java#L1063

**Comment by janis-ax** [comment]
Many thanks for your prompt answer. 
So we will leave it as default?

**Comment by exceptionfactory** [comment]
You're welcome @janis-ax. Yes, at this time, the `Created-By` field will remain static as it reflects the build tool as opposed to the author. For now, the NAR Manifest does not use additional fields. If this changes in the future, the ability to set a field based on the author could be considered.
