### ISSUE TITLE
Please suport Python 3.9

### ISSUE THREAD

**Issue by snowch** [datavolo-io/hatch-datavolo-nar#5]
Quite a lot of docker environments are running 3.9.  It would be great if this project could suport 3.9+

**Comment by exceptionfactory** [comment]
Thanks for the feedback on the NAR plugin @snowch.

As you noted in in issue #6, the current plugin implementation requires having the same Python version and architecture as the NiFi runtime environment.

In addition, the plugin itself uses Python [zipfile](https://docs.python.org/3/library/zipfile.html) features that were introduced in Python 3.11.

For these reasons, the initial target versions for the plugin were limited to Python 3.12 and 3.11. Although there are alternative approaches to workaround the zipfile features for older versions of Python, the focus of Python support will remain on the latest Python version, and one version previous.

Thanks again for using the plugin and providing the feedback!
