### ISSUE TITLE
Documentation - add note for the build machine to have the same architecture as the destination.

### ISSUE THREAD

**Issue by snowch** [datavolo-io/hatch-datavolo-nar#6]
It would be great to have this documentation.

**Comment by exceptionfactory** [comment]
Thanks for the feedback @snowch! We will look at updating the documentation to note the need for build machine to have the same architecture as the runtime environment.

**Comment by exceptionfactory** [comment]
Thanks again for the feedback @snowch, the documentation is updated in pull request #8.
